spring.application.name=local-service-finder

spring.datasource.url=jdbc:mysql://local-service-finder-local-service-finder.j.aivencloud.com:26305/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiry-ms=3600000

server.port=${PORT:8080}

razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}